# Generated by Django 5.0.3 on 2025-08-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Datanalyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataanalysiscache',
            name='chart_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='圖表配置'),
        ),
        migrations.AlterField(
            model_name='dataanalysiscache',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='分析數據'),
        ),
    ]
