# Generated by Django 5.0.3 on 2025-08-24 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datanalyze', '0002_alter_dataanalysiscache_chart_config_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataAnalysisCache',
        ),
    ]
