# Generated by Django 5.0.3 on 2025-08-24 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Datanalyze', '0003_delete_dataanalysiscache'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('reach_analysis', '觸及率分析'), ('like_analysis', '按讚次數分析'), ('share_analysis', '分享次數分析'), ('view_time_analysis', '停留時間分析'), ('save_analysis', '收藏次數分析'), ('comment_analysis', '留言數量分析')], max_length=20, verbose_name='分析類型')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='分析數據')),
                ('chart_config', models.JSONField(blank=True, default=dict, verbose_name='圖表配置')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_analysis_caches', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '數據分析緩存',
                'verbose_name_plural': '數據分析緩存',
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'analysis_type')},
            },
        ),
    ]
