# Generated by Django 5.0.3 on 2025-08-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='platform',
            field=models.CharField(blank=True, max_length=20, verbose_name='社群平台'),
        ),
    ]
