# Generated by Django 4.2.7 on 2025-08-26 17:00:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0003_add_new_fields'),
    ]

    operations = [
        # 刪除舊的排程相關表
        migrations.DeleteModel(
            name='ScheduleExecution',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleTemplate',
        ),
        
        # 創建新的排程發文設定表
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='排程名稱')),
                ('description', models.TextField(blank=True, verbose_name='排程描述')),
                ('status', models.CharField(choices=[('active', '啟用'), ('paused', '暫停'), ('cancelled', '取消')], default='active', max_length=20, verbose_name='狀態')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('execution_days', models.JSONField(default=list, help_text='例如：["monday", "tuesday", "wednesday"]', verbose_name='執行日期')),
                ('posting_times', models.JSONField(default=list, help_text='例如：["09:00", "14:00", "18:00"]', verbose_name='發文時間')),
                ('platform', models.CharField(max_length=20, verbose_name='社群平台')),
                ('message_content', models.TextField(verbose_name='發文內容')),
                ('template_images', models.JSONField(default=list, help_text='圖片URL和排序信息', verbose_name='模板圖片')),
                ('target_communities', models.JSONField(default=list, help_text='社團信息列表', verbose_name='目標社團')),
                ('total_executions', models.PositiveIntegerField(default=0, verbose_name='總執行次數')),
                ('successful_executions', models.PositiveIntegerField(default=0, verbose_name='成功執行次數')),
                ('failed_executions', models.PositiveIntegerField(default=0, verbose_name='失敗執行次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('last_execution_time', models.DateTimeField(blank=True, null=True, verbose_name='最後執行時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='Accounts.user', verbose_name='使用者')),
            ],
            options={
                'verbose_name': '排程發文設定',
                'verbose_name_plural': '排程發文設定',
                'ordering': ['-created_at'],
            },
        ),
        
        # 創建新的排程執行記錄表
        migrations.CreateModel(
            name='ScheduleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='執行狀態')),
                ('scheduled_time', models.DateTimeField(verbose_name='預定執行時間')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始執行時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('result_message', models.TextField(blank=True, verbose_name='執行結果訊息')),
                ('error_details', models.TextField(blank=True, verbose_name='錯誤詳情')),
                ('execution_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='執行時長(秒)')),
                ('posts_published', models.PositiveIntegerField(default=0, verbose_name='成功發布貼文數')),
                ('posts_failed', models.PositiveIntegerField(default=0, verbose_name='失敗發布貼文數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='Crawler.schedule', verbose_name='排程設定')),
            ],
            options={
                'verbose_name': '排程執行記錄',
                'verbose_name_plural': '排程執行記錄',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
