# Generated by Django 5.0.3 on 2025-08-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crawler', '0005_alter_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='template',
            field=models.ForeignKey(blank=True, help_text='選擇要使用的貼文模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='Crawler.posttemplate', verbose_name='使用的模板'),
        ),
    ]
