# Generated by Django 5.0.3 on 2025-08-24 23:26

import Accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='付費用戶'),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='付費到期時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.avatar_upload_to, verbose_name='頭像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='個人簡介'),
        ),
        migrations.CreateModel(
            name='WebsiteCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('line', 'Line'), ('wechat', 'WeChat'), ('other', '其他')], max_length=20, verbose_name='網站名稱')),
                ('website_url', models.URLField(verbose_name='網站網址')),
                ('cookie_data', models.JSONField(blank=True, default=dict, verbose_name='Cookie資料')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '網站Cookie',
                'verbose_name_plural': '網站Cookie',
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'website')},
            },
        ),
    ]
