# Generated by Django 5.0.3 on 2025-08-18 17:09

import Accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.avatar_upload_to, verbose_name='頭像'),
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='社團名稱')),
                ('community_type', models.CharField(choices=[('facebook_group', 'Facebook社團'), ('facebook_page', 'Facebook粉絲頁'), ('instagram_account', 'Instagram帳號'), ('discord_server', 'Discord伺服器'), ('telegram_channel', 'Telegram頻道'), ('line_group', 'Line群組'), ('wechat_group', '微信群組'), ('forum', '論壇'), ('blog', '部落格'), ('other', '其他')], max_length=20, verbose_name='社團類型')),
                ('url', models.URLField(verbose_name='社團連結')),
                ('description', models.TextField(blank=True, verbose_name='社團描述')),
                ('member_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='成員數量')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_public', models.BooleanField(default=True, verbose_name='是否公開')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='最後活動時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='標籤')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communities', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '社團',
                'verbose_name_plural': '社團',
                'ordering': ['-last_activity', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='Accounts_co_user_id_4ac5a6_idx'), models.Index(fields=['community_type', 'is_active'], name='Accounts_co_communi_8a80dd_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebsiteCookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('line', 'Line'), ('wechat', 'WeChat'), ('other', '其他')], max_length=20, verbose_name='網站名稱')),
                ('website_url', models.URLField(verbose_name='網站網址')),
                ('cookie_data', models.JSONField(verbose_name='Cookie資料')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('notes', models.TextField(blank=True, verbose_name='備註')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '網站Cookie',
                'verbose_name_plural': '網站Cookie',
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'website')},
            },
        ),
    ]
