# Generated by Django 5.0.3 on 2025-08-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_is_premium_user_premium_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='community_type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram_account', 'Instagram帳號'), ('discord_server', 'Discord伺服器'), ('telegram_channel', 'Telegram頻道'), ('line_group', 'Line群組'), ('wechat_group', '微信群組'), ('forum', '論壇'), ('blog', '部落格'), ('other', '其他')], max_length=20, verbose_name='社團類型'),
        ),
    ]
