# Generated by Django 5.0.3 on 2025-08-23 23:26

import Accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_community_community_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='模板標題')),
                ('content', models.TextField(verbose_name='文案內容')),
                ('hashtags', models.TextField(blank=True, verbose_name='標籤')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '貼文模板',
                'verbose_name_plural': '貼文模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PostTemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=Accounts.models.template_image_upload_to, verbose_name='圖片')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='替代文字')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Accounts.posttemplate', verbose_name='模板')),
            ],
            options={
                'verbose_name': '模板圖片',
                'verbose_name_plural': '模板圖片',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='posttemplate',
            index=models.Index(fields=['user', 'is_active'], name='Accounts_po_user_id_016e19_idx'),
        ),
        migrations.AddIndex(
            model_name='posttemplateimage',
            index=models.Index(fields=['template', 'order'], name='Accounts_po_templat_dbf85e_idx'),
        ),
    ]
