# Generated by Django 5.0.3 on 2025-08-23 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_posttemplate_posttemplateimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttemplate',
            name='category',
            field=models.CharField(choices=[('product', '商品推廣'), ('event', '活動宣傳'), ('announcement', '公告通知'), ('tutorial', '教學指南'), ('review', '心得分享'), ('news', '新聞資訊'), ('other', '其他')], default='other', max_length=20, verbose_name='類別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='個人簡介'),
        ),
    ]
