# Generated by Django 5.0.3 on 2025-08-23 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_posttemplate_category_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttemplate',
            name='category',
        ),
    ]
