# Generated by Django 5.0.3 on 2025-08-24 00:46

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_remove_posttemplate_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplateimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.template_image_upload_to, verbose_name='圖片'),
        ),
    ]
