# Generated by Django 5.0.3 on 2025-08-24 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_alter_posttemplateimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttemplate',
            name='hashtags',
            field=models.JSONField(blank=True, default=list, verbose_name='標籤'),
        ),
        migrations.AlterField(
            model_name='websitecookie',
            name='cookie_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Cookie資料'),
        ),
        migrations.CreateModel(
            name='DataAnalysisCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('reach_analysis', '觸及率分析'), ('like_analysis', '按讚次數分析'), ('share_analysis', '分享次數分析'), ('view_time_analysis', '停留時間分析'), ('save_analysis', '收藏次數分析'), ('comment_analysis', '留言數量分析')], max_length=20, verbose_name='分析類型')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='分析數據')),
                ('chart_config', models.JSONField(blank=True, default=dict, verbose_name='圖表配置')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最後更新時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_analysis_caches', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '數據分析緩存',
                'verbose_name_plural': '數據分析緩存',
                'ordering': ['-last_updated'],
                'indexes': [models.Index(fields=['user', 'analysis_type'], name='Accounts_da_user_id_64c31c_idx'), models.Index(fields=['analysis_type', 'last_updated'], name='Accounts_da_analysi_5c151b_idx')],
                'unique_together': {('user', 'analysis_type')},
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('discord', 'Discord'), ('telegram', 'Telegram'), ('line', 'Line'), ('wechat', 'WeChat'), ('other', '其他')], max_length=20, verbose_name='平台')),
                ('post_id', models.CharField(max_length=255, verbose_name='貼文ID')),
                ('content', models.TextField(blank=True, verbose_name='貼文內容')),
                ('post_url', models.URLField(blank=True, verbose_name='貼文連結')),
                ('reach_count', models.PositiveIntegerField(default=0, verbose_name='觸及人數')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='按讚次數')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='分享次數')),
                ('view_time_seconds', models.PositiveIntegerField(default=0, verbose_name='停留時間(秒)')),
                ('save_count', models.PositiveIntegerField(default=0, verbose_name='收藏次數')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='留言數量')),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='互動率(%)')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='發布時間')),
                ('data_collected_at', models.DateTimeField(auto_now=True, verbose_name='數據收集時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '社交媒體貼文',
                'verbose_name_plural': '社交媒體貼文',
                'ordering': ['-data_collected_at', '-posted_at'],
                'indexes': [models.Index(fields=['user', 'platform'], name='Accounts_so_user_id_dd518d_idx'), models.Index(fields=['platform', 'data_collected_at'], name='Accounts_so_platfor_2695fb_idx'), models.Index(fields=['posted_at'], name='Accounts_so_posted__8c8fb5_idx')],
                'unique_together': {('user', 'platform', 'post_id')},
            },
        ),
    ]
