# Generated by Django 5.0.3 on 2025-08-24 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_alter_posttemplate_hashtags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='模板名稱')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('template_type', models.CharField(choices=[('daily_posting', '每日發文'), ('weekly_campaign', '每週活動'), ('monthly_report', '每月報告'), ('custom', '自定義')], default='custom', max_length=20, verbose_name='模板類型')),
                ('default_frequency', models.CharField(choices=[('once', '單次'), ('hourly', '每小時'), ('daily', '每天'), ('weekly', '每週'), ('monthly', '每月'), ('custom', '自定義')], default='daily', max_length=20, verbose_name='預設頻率')),
                ('default_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='預設間隔(分鐘)')),
                ('default_content_template', models.TextField(blank=True, verbose_name='預設內容模板')),
                ('default_hashtags', models.JSONField(blank=True, default=list, verbose_name='預設標籤')),
                ('default_platforms', models.JSONField(default=list, verbose_name='預設平台')),
                ('default_communities', models.JSONField(default=list, verbose_name='預設社團')),
                ('usage_count', models.PositiveIntegerField(default=0, verbose_name='使用次數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '排程模板',
                'verbose_name_plural': '排程模板',
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='排程名稱')),
                ('description', models.TextField(blank=True, verbose_name='排程描述')),
                ('status', models.CharField(choices=[('active', '啟用'), ('paused', '暫停'), ('disabled', '停用'), ('completed', '已完成'), ('expired', '已過期')], default='active', max_length=20, verbose_name='排程狀態')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('start_time', models.DateTimeField(verbose_name='開始時間')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='結束時間')),
                ('frequency', models.CharField(choices=[('once', '單次'), ('hourly', '每小時'), ('daily', '每天'), ('weekly', '每週'), ('monthly', '每月'), ('custom', '自定義')], default='daily', max_length=20, verbose_name='執行頻率')),
                ('interval_minutes', models.PositiveIntegerField(default=60, verbose_name='執行間隔(分鐘)')),
                ('next_execution', models.DateTimeField(verbose_name='下次執行時間')),
                ('custom_content', models.TextField(blank=True, verbose_name='自定義內容')),
                ('custom_hashtags', models.JSONField(blank=True, default=list, verbose_name='自定義標籤')),
                ('use_template_images', models.BooleanField(default=True, verbose_name='使用模板圖片')),
                ('additional_images', models.JSONField(blank=True, default=list, verbose_name='額外圖片路徑')),
                ('platforms', models.JSONField(default=list, verbose_name='目標平台')),
                ('target_communities', models.JSONField(default=list, verbose_name='目標社團/頁面')),
                ('total_executions', models.PositiveIntegerField(default=0, verbose_name='總執行次數')),
                ('successful_executions', models.PositiveIntegerField(default=0, verbose_name='成功執行次數')),
                ('failed_executions', models.PositiveIntegerField(default=0, verbose_name='失敗執行次數')),
                ('last_execution_time', models.DateTimeField(blank=True, null=True, verbose_name='最後執行時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.posttemplate', verbose_name='文案模板')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '排程設定',
                'verbose_name_plural': '排程設定',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '執行中'), ('completed', '已完成'), ('failed', '失敗'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='執行狀態')),
                ('scheduled_time', models.DateTimeField(verbose_name='預定執行時間')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='開始執行時間')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成時間')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功發布數')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='失敗發布數')),
                ('total_count', models.PositiveIntegerField(default=0, verbose_name='總發布數')),
                ('execution_log', models.JSONField(blank=True, default=dict, verbose_name='執行日誌')),
                ('error_messages', models.JSONField(blank=True, default=list, verbose_name='錯誤訊息')),
                ('published_posts', models.JSONField(blank=True, default=list, verbose_name='已發布貼文')),
                ('reach_count', models.PositiveIntegerField(default=0, verbose_name='觸及人數')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='按讚數')),
                ('share_count', models.PositiveIntegerField(default=0, verbose_name='分享數')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='留言數')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='Accounts.schedule', verbose_name='排程')),
            ],
            options={
                'verbose_name': '排程執行記錄',
                'verbose_name_plural': '排程執行記錄',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['user', 'status'], name='Accounts_sc_user_id_182d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['next_execution'], name='Accounts_sc_next_ex_08fbda_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status', 'next_execution'], name='Accounts_sc_status_b69d7f_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexecution',
            index=models.Index(fields=['schedule', 'status'], name='Accounts_sc_schedul_232e6a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexecution',
            index=models.Index(fields=['scheduled_time'], name='Accounts_sc_schedul_16651c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleexecution',
            index=models.Index(fields=['status', 'scheduled_time'], name='Accounts_sc_status_a5a48a_idx'),
        ),
    ]
